version: '3.8'

services:
  rog_ai_guardian:
    build:
      context: .
      dockerfile: Dockerfile
      network: host
    image: smart-wol-cam:v11
    container_name: rog_ai_guardian
    restart: always
    network_mode: "host"
    environment:
      - RTSP_URL=${RTSP_URL}
      - ROG_IP=${ROG_IP}
      - MAC_ADDRESS=${MAC_ADDRESS}
      - AWAY_TIME_LIMIT=${AWAY_TIME_LIMIT}
      - TOLERANCE=${TOLERANCE}
      - PC_USER=${PC_USER}
      - PC_PASS=${PC_PASS}
      - YS_APP_KEY=${YS_APP_KEY}
      - YS_APP_SECRET=${YS_APP_SECRET}
      - YS_DEVICE_SERIAL=${YS_DEVICE_SERIAL}