version: '3.8'

services:
  rog_ai_guardian:
    build:
      context: .
      dockerfile: Dockerfile
      network: host          # 👈 【关键新增】让 Docker 在打包编译时，直接使用宿主机的物理网络！

    container_name: rog_ai_guardian
    restart: always
    network_mode: "host"     # 这是运行时使用的网络
    environment:
      - RTSP_URL=${RTSP_URL}
      - ROG_IP=${ROG_IP}
      - MAC_ADDRESS=${MAC_ADDRESS}
      - AWAY_TIME_LIMIT=${AWAY_TIME_LIMIT}
      - PC_USER=${PC_USER}
      - PC_PASS=${PC_PASS}